---
# handlers file for setup-apache

   - name: apache restart
     service:
          name: httpd
          state: restarted



   - name: apache2 restart
     service:
          name: apache2
          state: restarted



   - name: apache restart
     service:
          name: httpd
          state: restarted



   - name: apache2 restart
     service:
          name: apache2
          state: restarted

