---
- name: this playbook  install apahce
  hosts: webserver
  become: true
  tasks:
   - name: install apache server
     yum:
       name: httpd
       state: installed
     notify: apache restart
  handlers:
   - name: apache restart
     service:
          name: httpd
          state: started
