---
- name: install packages
  hosts: webserver
  become: true
  tasks:
          - name: install apache through yum module
            yum:
                    name: tree
                    state: installed
