---
- name: install apache on ubuntu
  hosts: dbserver
  become: true
  tasks:
          - name: apache2 on ubuntu
            apt:
                    name: apache2
                    state: present



          - name: started apache2
            service:
                   name: apache2
                   state: started


