---
- name: this playbook  install apahce
  hosts: all
  #  become: true
  tasks:
   - name: install apache server
     yum:
       name: httpd
       state: installed

     when: ansible_os_family == "RedHat"
     #    tags: install_apache

   - name: apache restart
     service:
          name: httpd
          state: started
     
     when: ansible_os_family == "RedHat"
     ignore_errors: yes
     #    tags: start_apache

   - name: install apache2 server
     apt:
       name: apache2
       state: present
       

     when: ansible_os_family == "Debian"
     #    tags: install_apache

   - name: apache2 restart
     service:
          name: apache2
          state: started

     when: ansible_os_family == "Debian"
     #     tags: start_apache
   - name: copy file on remote server
     copy:
       src: /home/ansadmin/index.html
       dest: /var/www/html/
       mode: 0666


     when: ansible_os_family == "RedHat"

   - name: copy file on ubuntu
     copy:
       src: /home/ansadmin/ansible/index.html
       dest: /var/www/html/
       mode: 0666
     when: ansible_os_family == "Debian"

